version: "3.9"
services:
  app:
    build: ./docker/php
    volumes:
      - ./../ci:/var/www/html

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./../ci:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
    
volumes:
  db-store:
